---
services:
  tkvpp-node-standalone:
    image: tinykvpp-clang:latest
    security_opt:
      - seccomp:unconfined
    container_name: tkvpp-node-standalone
    command: ["/app/tkvpp", "-c", "/app/config.json"]
    ports:
      - "9891:9891"
    volumes:
      - ./assets/tkvpp_config_standalone.json:/app/config.json
      - tkvpp-node-standalone:/var/tkvpp
volumes:
  tkvpp-node-standalone:
